//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyNCSConsole {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class NCSSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static NCSSettings defaultInstance = ((NCSSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NCSSettings())));
        
        public static NCSSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170000.00")]
        public decimal PrinterTarget {
            get {
                return ((decimal)(this["PrinterTarget"]));
            }
            set {
                this["PrinterTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000.00")]
        public decimal CopierTarget {
            get {
                return ((decimal)(this["CopierTarget"]));
            }
            set {
                this["CopierTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.516666")]
        public decimal QBSPerc {
            get {
                return ((decimal)(this["QBSPerc"]));
            }
            set {
                this["QBSPerc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("noreply@qbsi-xerox.com")]
        public string FromEmail {
            get {
                return ((string)(this["FromEmail"]));
            }
            set {
                this["FromEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.8.1.34")]
        public string SMTPServer {
            get {
                return ((string)(this["SMTPServer"]));
            }
            set {
                this["SMTPServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nwgdailyncs@qbsi-xerox.com")]
        public string ToEmail {
            get {
                return ((string)(this["ToEmail"]));
            }
            set {
                this["ToEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NWGSQL08;Initial Catalog=USQLTransitory;User ID=NWGUSQL;password=Silv" +
            "er99;Connection Timeout=3000")]
        public string SQLConString {
            get {
                return ((string)(this["SQLConString"]));
            }
            set {
                this["SQLConString"] = value;
            }
        }
    }
}
